/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Single source of truth JSON Schema for YAML, TypeScript, and Python interfaces
 */
export type InfrastructureCostModelRepresentation = {
  [k: string]: unknown;
} & {
  /**
   * Schema version
   */
  version: "1.0";
  /**
   * PEP 440 version specifier naming the engine version this model needs (e.g. ">=0.2.0"). The engine refuses to price the model when the running version does not satisfy the specifier, instead of silently dropping fields it does not understand or pricing them at $0. Absent means no requirement.
   */
  requiresEngine?: string;
  workflow?: Workflow;
  /**
   * Multiple independent workflows sharing the same infrastructure nodes. Each workflow has its own entry point, frequency, and optional parameters. Costs are aggregated across all workflows.
   *
   * @minItems 1
   */
  workflows?: [Workflow, ...Workflow[]];
  nodes: {
    [k: string]: Node;
  };
  edges?: Edge[];
  [k: string]: unknown;
};
/**
 * Node type determines valid usage metrics and edge permissions. External nodes are leaf nodes for third-party services (Stripe, Twilio).
 */
export type NodeType = "compute" | "storage" | "routing" | "external";

export interface Workflow {
  /**
   * Workflow identifier
   */
  name: string;
  /**
   * Address of the entry node (receives external traffic)
   */
  entry: string;
  frequency: {
    /**
     * Time unit for entry frequency
     */
    unit: "perSecond" | "perMinute" | "perHour" | "perDay" | "perWeek" | "perMonth";
    /**
     * Invocation rate at the entry node
     */
    value: number;
    [k: string]: unknown;
  };
  /**
   * Symbolic variables for what-if analysis
   */
  parameters?: {
    [k: string]: number;
  };
  [k: string]: unknown;
}
export interface Node {
  nodeType: NodeType;
  /**
   * Infrastructure resource address (Terraform: aws_lambda_function.foo, Pulumi: aws:lambda:Function:foo, CDK: AWS::Lambda::Function/myApi/getItems)
   */
  resourceAddress: string;
  /**
   * Cloud or SaaS provider (e.g., aws, gcp, github)
   */
  provider?: string;
  /**
   * Service name (e.g., AWSLambda, DynamoDB)
   */
  service?: string;
  /**
   * Cloud region (e.g., us-east-1)
   */
  region?: string;
  /**
   * Resource settings from the infrastructure-as-code extraction, such as the model of an Azure OpenAI deployment. The resource handler reads them to pick the catalog rows that price the node.
   */
  config?: {
    [k: string]: unknown;
  };
  usageMetrics?: {
    [k: string]: UsageMetric;
  };
  /**
   * Pricing model type. Percentage: fixed + percentage of transaction volume (e.g., Stripe: 2.9% + $0.30).
   */
  pricingModel?: "tiered" | "flat" | "token_based" | "percentage";
  /**
   * Pricing rates per usage metric (used when price catalog unavailable)
   */
  pricingRates?: {
    [k: string]: number;
  };
  /**
   * When true, ALL usageMetrics values are flat monthly totals (escape hatch, per DP#9) — equivalent to marking every metric fixed. When false (default), values are per-invocation multipliers applied to the derived invocation count. For a resource with both a fixed and a usage-driven dimension, prefer the per-metric 'fixed' flag instead. A node carrying any fixed cost is always-on: it is costed without a synthetic incoming edge and is not reported as unreachable.
   */
  flatOverride?: boolean;
  [k: string]: unknown;
}
export interface UsageMetric {
  /**
   * Unit of measurement (e.g., requests, ms, MB, tokens)
   */
  unit: string;
  description?: string;
  /**
   * Per-invocation multiplier. Multiplied by the derived invocation count to compute total consumption. When this metric is fixed (or flatOverride is true on the containing node), this value is used directly as a flat monthly total instead.
   */
  value?: number;
  /**
   * When true, this metric is a fixed (always-on) monthly total: its value is used directly and is NOT scaled by the derived invocation count. This lets one node carry both a fixed dimension (e.g. NAT gateway hours, ALB-hours) and a usage-driven dimension (e.g. GB processed, LCUs) without splitting into two nodes (Issue #196).
   */
  fixed?: boolean;
  /**
   * Count only the calls that arrive over edges of this type. A DynamoDB table sets edgeType read on its read-request metric and edgeType write on its write-request metric, so each call is charged once (Issue #313). An edge without a type is an invoke edge, and traffic at the entry node counts as invoke. Without edgeType, the metric counts every call. A fixed metric ignores it.
   */
  edgeType?: "read" | "write" | "invoke";
  /**
   * SaaS pricing shape name (e.g., flat_subscription, per_unit_flat, free_tier, transactional)
   */
  shape?: string;
  /**
   * Flat rate for subscription or per-unit flat shapes
   */
  rate?: number;
  /**
   * Free tier allowance
   */
  free?: number;
  /**
   * Overage rate for free tier
   */
  overage?: number;
  /**
   * Percentage rate for transactional shapes
   */
  percentage_rate?: number;
  /**
   * Per-call fee for transactional shapes
   */
  per_call?: number;
  /**
   * Subscription cost for credit pool
   */
  subscription?: number;
  /**
   * Credits included in subscription
   */
  includedCredits?: number;
  /**
   * Value per credit
   */
  creditValue?: number;
  /**
   * Stepped overage bands for free_tier, walked in order above the free allowance. Each entry carries an inclusive upper bound and the rate charged below it; omit up_to on the final entry for an open-ended band.
   */
  tiers?: {
    /**
     * Upper bound of this band, in billable units above the free allowance. Omit on the final entry for an open-ended band.
     */
    up_to?: number;
    /**
     * Price per unit within this band
     */
    rate: number;
  }[];
  /**
   * Value of one transaction for transactional shapes. Each transaction is charged volume × percentage_rate, plus fixed_per_transaction and per_call.
   */
  volume?: number;
  /**
   * Flat fee per transaction for transactional shapes, multiplied by the quantity
   */
  fixed_per_transaction?: number;
}
export interface Edge {
  /**
   * Source node resource address
   */
  from: string;
  /**
   * Target node resource address
   */
  to: string;
  /**
   * Call rate: how many times parent invokes child per parent invocation
   */
  rate: number;
  /**
   * Type of call (read/write for database operations, invoke for compute)
   */
  type?: "read" | "write" | "invoke";
  dataSize?: {
    unit?: string;
    /**
     * Average bytes per call
     */
    average?: number;
    minimum?: number;
    maximum?: number;
    [k: string]: unknown;
  };
  /**
   * Token flow for LLM-based edges. Input tokens flow downstream to LLM nodes; output tokens flow upstream to orchestration nodes.
   */
  tokenFlow?: {
    /**
     * Input/prompt tokens flowing through this edge per parent invocation
     */
    input?: number;
    /**
     * Output/completion tokens flowing through this edge per parent invocation
     */
    output?: number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
