/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Single source of truth JSON Schema for YAML, TypeScript, and Python interfaces
 */
export type InfrastructureCostModelRepresentation = {
  [k: string]: unknown;
} & {
  /**
   * Schema version
   */
  version: "1.0";
  workflow?: Workflow;
  /**
   * Multiple independent workflows sharing the same infrastructure nodes. Each workflow has its own entry point, frequency, and optional parameters. Costs are aggregated across all workflows.
   *
   * @minItems 1
   */
  workflows?: [Workflow, ...Workflow[]];
  nodes: {
    [k: string]: Node;
  };
  edges?: Edge[];
  [k: string]: unknown;
};
/**
 * Node type determines valid usage metrics and edge permissions. External nodes are leaf nodes for third-party services (Stripe, Twilio).
 */
export type NodeType = "compute" | "storage" | "routing" | "external";

export interface Workflow {
  /**
   * Workflow identifier
   */
  name: string;
  /**
   * Address of the entry node (receives external traffic)
   */
  entry: string;
  frequency: {
    /**
     * Time unit for entry frequency
     */
    unit: "perSecond" | "perMinute" | "perHour" | "perDay" | "perWeek" | "perMonth";
    /**
     * Invocation rate at the entry node
     */
    value: number;
    [k: string]: unknown;
  };
  /**
   * Symbolic variables for what-if analysis
   */
  parameters?: {
    [k: string]: number;
  };
  [k: string]: unknown;
}
export interface Node {
  nodeType: NodeType;
  /**
   * Infrastructure resource address (Terraform: aws_lambda_function.foo, Pulumi: aws:lambda:Function:foo, CDK: AWS::Lambda::Function/myApi/getItems)
   */
  resourceAddress: string;
  /**
   * Cloud provider
   */
  provider?: "aws" | "azure" | "gcp" | "bedrock" | "openai";
  /**
   * Service name (e.g., AWSLambda, DynamoDB)
   */
  service?: string;
  /**
   * Cloud region (e.g., us-east-1)
   */
  region?: string;
  usageMetrics?: {
    [k: string]: UsageMetric;
  };
  /**
   * Pricing model type. Percentage: fixed + percentage of transaction volume (e.g., Stripe: 2.9% + $0.30).
   */
  pricingModel?: "tiered" | "flat" | "token_based" | "percentage";
  /**
   * Pricing rates per usage metric (used when price catalog unavailable)
   */
  pricingRates?: {
    [k: string]: number;
  };
  /**
   * When true, usageMetrics values are flat monthly totals (escape hatch, per DP#9). When false (default), values are per-invocation multipliers applied to the derived invocation count.
   */
  flatOverride?: boolean;
  [k: string]: unknown;
}
export interface UsageMetric {
  /**
   * Unit of measurement (e.g., requests, ms, MB, tokens)
   */
  unit: string;
  description?: string;
  /**
   * Per-invocation multiplier. Multiplied by the derived invocation count to compute total consumption. When flatOverride is true on the containing node, this value is used directly as a flat monthly total instead.
   */
  value?: number;
  [k: string]: unknown;
}
export interface Edge {
  /**
   * Source node resource address
   */
  from: string;
  /**
   * Target node resource address
   */
  to: string;
  /**
   * Call rate: how many times parent invokes child per parent invocation
   */
  rate: number;
  /**
   * Type of call (read/write for database operations, invoke for compute)
   */
  type?: "read" | "write" | "invoke";
  dataSize?: {
    unit?: string;
    /**
     * Average bytes per call
     */
    average?: number;
    minimum?: number;
    maximum?: number;
    [k: string]: unknown;
  };
  /**
   * Token flow for LLM-based edges. Input tokens flow downstream to LLM nodes; output tokens flow upstream to orchestration nodes.
   */
  tokenFlow?: {
    /**
     * Input/prompt tokens flowing through this edge per parent invocation
     */
    input?: number;
    /**
     * Output/completion tokens flowing through this edge per parent invocation
     */
    output?: number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
