"""Generate typed resource handler classes from terraform provider schemas.

Per DP#10: Resource types must be generated from IaC provider schemas,
not hand-written. This module generates Python resource handler classes
with from_address, extract_tf, extract_pulumi, and extract_cdk methods.
"""

import textwrap
from typing import Optional

from .schema_reader import ResourceSchema, SchemaAttribute


class CodeGenerator:
    """Generates typed Python resource handler classes from parsed schemas.

    Usage:
        gen = CodeGenerator()
        source = gen.generate_handler(resource_schema)
        # Write source to a .py file or return as string
    """

    # Mapping from terraform types to valid_metrics entries
    TYPE_TO_METRIC: dict[str, str] = {
        "number": "numeric",
        "string": "text",
        "bool": "flag",
    }

    # Node type classification rules based on resource type patterns
    NODE_CLASSIFICATION: dict[str, str] = {
        "function": "compute",
        "_function": "compute",
        "table": "storage",
        "bucket": "storage",
        "database": "storage",
        "queue": "storage",
        "topic": "routing",
        "api": "routing",
        "gateway": "routing",
        "event": "routing",
    }

    def __init__(self, indent: int = 4):
        self.indent = indent

    def generate_handler(self, resource: ResourceSchema) -> str:
        """Generate a complete Python resource handler module.

        Args:
            resource: Parsed resource schema from terraform provider schema.

        Returns:
            Python source code for the resource handler class.
        """
        class_name = self._class_name(resource.resource_type)
        node_type = self._infer_node_type(resource.resource_type)
        base_class = self._node_type_to_base(node_type)
        provider = resource.provider

        lines = []
        lines.append('"""Auto-generated resource handler for {}.'.format(
            resource.resource_type))
        lines.append('')
        lines.append('Generated by codegen from terraform provider schema v{}.'.format(
            resource.version))
        lines.append('Per DP#10: Do not edit by hand. Regenerate from schema.'.format(
            resource.version))
        lines.append('"""')
        lines.append('')
        lines.append('from typing import Optional')
        lines.append('')
        lines.append('from .types import {}, ResourceExtract'.format(base_class))
        lines.append('')
        lines.append('')
        lines.append('class {}({}):'.format(class_name, base_class))
        lines.append('    """{} resource - {}.'.format(
            resource.resource_type.replace("_", " ").title(),
            node_type))
        lines.append('')
        lines.append('    Generated from terraform provider schema v{}.'.format(
            resource.version))
        lines.append('    """')
        lines.append('')
        # valid_metrics property
        lines.append('    @property')
        lines.append('    def valid_metrics(self) -> list[str]:')
        metric_names = self._derive_metrics(resource.attributes)
        if metric_names:
            lines.append('        return [{}]'.format(
                ', '.join(repr(m) for m in metric_names)))
        else:
            lines.append('        return []')
        lines.append('')

        # from_address classmethod
        lines.append('    @classmethod')
        lines.append('    def from_address(cls, resource_address: str) -> Optional["{}"]:'.format(
            class_name))
        lines.append('        """Parse resource address to determine if it matches {}."""'.format(
            resource.resource_type))
        prefix_patterns = self._address_patterns(resource.resource_type, provider)
        condition = self._build_address_condition(prefix_patterns)
        lines.extend(condition)
        lines.append('')

        # extract_tf
        lines.extend(self._generate_extract_method(
            class_name, resource, "tf", "terraform", provider))

        # extract_pulumi
        lines.extend(self._generate_extract_method(
            class_name, resource, "pulumi", "pulumi", provider))

        # extract_cdk
        lines.extend(self._generate_extract_method(
            class_name, resource, "cdk", "cdk", provider))

        return '\n'.join(lines)

    def _class_name(self, resource_type: str) -> str:
        """Derive a PascalCase class name from a terraform resource type."""
        # aws_lambda_function -> LambdaFunction
        # google_cloudfunctions_function -> CloudfunctionsFunction
        # azurerm_function_app -> FunctionApp
        parts = resource_type.split("_")
        # Strip provider prefix (aws_, google_, azurerm_)
        if parts[0] in ("aws", "google", "azurerm"):
            parts = parts[1:]
        return "".join(p.capitalize() for p in parts)

    def _infer_node_type(self, resource_type: str) -> str:
        """Infer node type from resource type name patterns."""
        for pattern, node_type in self.NODE_CLASSIFICATION.items():
            if pattern in resource_type.lower():
                return node_type
        return "compute"  # default

    def _node_type_to_base(self, node_type: str) -> str:
        """Map node type to base class name."""
        mapping = {
            "compute": "ComputeResource",
            "storage": "StorageResource",
            "routing": "RoutingResource",
            "external": "ExternalResource",
        }
        return mapping.get(node_type, "ComputeResource")

    def _derive_metrics(self, attributes: list[SchemaAttribute]) -> list[str]:
        """Derive valid_metrics from schema attributes.

        Converts attribute names to camelCase metric names:
        - memory_size -> memorySize
        - read_capacity -> readCapacity
        """
        metrics = []
        for attr in attributes:
            if attr.computed and not attr.required:
                continue  # Skip computed-only attributes
            # Convert snake_case to camelCase
            parts = attr.name.split("_")
            metric = parts[0] + "".join(p.capitalize() for p in parts[1:])
            metrics.append(metric)
        return metrics

    def _address_patterns(self, resource_type: str, provider: str) -> list[tuple[str, str]]:
        """Generate address patterns for the three IaC formats.

        Returns list of (format_name, pattern_string) tuples.
        """
        patterns = []

        # Terraform pattern
        patterns.append(("terraform", "{}.<name>".format(resource_type)))

        # Pulumi patterns by provider
        pulumi_map = {
            "aws": "aws:{}:".format(self._pulumi_type(resource_type)),
            "google": "google:{}:".format(self._pulumi_type(resource_type, prefix="gcp")),
            "azurerm": "azure:{}:".format(self._pulumi_type(resource_type, prefix="azure")),
        }
        pulumi_prefix = pulumi_map.get(provider,
            "{}:{}:".format(provider, self._pulumi_type(resource_type)))
        patterns.append(("pulumi", pulumi_prefix))

        # CDK/CloudFormation pattern
        cdk_type = self._cdk_type(resource_type, provider)
        patterns.append(("cdk", cdk_type))

        return patterns

    def _pulumi_type(self, resource_type: str, prefix: str = "") -> str:
        """Convert terraform type to Pulumi type.

        aws_lambda_function -> aws:lambda:Function
        google_cloudfunctions_function -> google:cloudfunctions:Function
        """
        parts = resource_type.split("_")
        if parts[0] in ("aws", "google", "azurerm"):
            parts = parts[1:]
        # Capitalize resource name parts for Pulumi convention
        result = ":".join(parts)
        # Capitalize the last segment (resource name)
        segs = result.split(":")
        if segs:
            segs[-1] = segs[-1].capitalize()
        return ":".join(segs)

    def _cdk_type(self, resource_type: str, provider: str) -> str:
        """Convert terraform type to CloudFormation type.

        aws_lambda_function -> AWS::Lambda::Function
        google_cloudfunctions_function -> Google::CloudFunctions::Function
        """
        if provider == "aws":
            parts = resource_type.split("_")
            if parts[0] == "aws":
                parts = parts[1:]
            return "AWS::{}".format("::".join(p.capitalize() for p in parts))
        elif provider == "google":
            parts = resource_type.split("_")
            if parts[0] == "google":
                parts = parts[1:]
            return "Google::{}".format("::".join(p.capitalize() for p in parts))
        else:
            parts = resource_type.split("_")
            if parts[0] in ("azurerm", "azure"):
                parts = parts[1:]
            if provider == "azurerm":
                provider = "Azure"
            return "{}::{}".format(
                provider.capitalize(),
                "::".join(p.capitalize() for p in parts),
            )

    def _build_address_condition(self, patterns: list[tuple[str, str]]) -> list[str]:
        """Build the if/elif/else block for from_address()."""
        lines = []
        conditions = []

        for fmt_name, pattern in patterns:
            if fmt_name == "terraform":
                conditions.append(
                    'resource_address.startswith("{}.")'.format(
                        pattern.replace(".<name>", ""))
                )
            elif fmt_name == "pulumi":
                conditions.append(
                    '"{}" in resource_address'.format(pattern))
            elif fmt_name == "cdk":
                conditions.append(
                    '"{}" in resource_address'.format(pattern))

        if len(conditions) == 1:
            lines.append('        if {}:'.format(conditions[0]))
            lines.append('            return cls()')
            lines.append('        return None')
        else:
            first = conditions[0]
            lines.append('        if ({} or'.format(first))
            for cond in conditions[1:-1]:
                lines.append('                {} or'.format(cond))
            lines.append('                {}):'.format(conditions[-1]))
            lines.append('            return cls()')
            lines.append('        return None')

        return lines

    def _generate_extract_method(
        self, class_name: str, resource: ResourceSchema,
        method_suffix: str, source_format: str, provider: str
    ) -> list[str]:
        """Generate extract_tf, extract_pulumi, or extract_cdk method."""
        lines = []
        lines.append('    @classmethod')
        lines.append('    def extract_{}(cls, resource: dict) -> ResourceExtract:'.format(
            method_suffix))

        if method_suffix == "tf":
            lines.append('        """Extract from Terraform {} resource."""'.format(
                resource.resource_type))
            lines.append('        values = resource.get("values", {})')
            source = "values"
            addr_key = "address"
            region_expr = 'values.get("region")'
        elif method_suffix == "pulumi":
            lines.append('        """Extract from Pulumi resource."""')
            lines.append('        inputs = resource.get("inputs", {})')
            source = "inputs"
            addr_key = "id"
            region_expr = 'inputs.get("region")'
        else:  # cdk
            lines.append('        """Extract from CDK CloudFormation resource."""')
            lines.append('        properties = resource.get("Properties", {})')
            source = "properties"
            addr_key = "LogicalId"
            region_expr = 'properties.get("region")'

        lines.append('')
        lines.append('        return ResourceExtract(')
        lines.append('            resource_address=resource.get({}),'.format(repr(addr_key)))
        lines.append('            node_type="{}",'.format(
            self._infer_node_type(resource.resource_type)))
        lines.append('            provider="{}",'.format(provider))
        lines.append('            service="{}",'.format(
            self._service_name(resource.resource_type, provider)))
        lines.append('            region={},'.format(region_expr))

        lines.append('            config={')
        for attr in resource.attributes[:5]:  # Top 5 most important attributes
            key = attr.name
            # Map terraform key to IaC-specific key for pulumi/cdk
            if method_suffix == "pulumi":
                key = self._to_camel_case(attr.name)
            elif method_suffix == "cdk":
                key = self._to_pascal_case(attr.name)
            lines.append('                "{}": {}.get("{}"),'.format(
                attr.name, source, key))
        lines.append('            },')
        lines.append('        )')
        lines.append('')

        return lines

    def _service_name(self, resource_type: str, provider: str) -> str:
        """Derive a service name for catalog lookup.

        aws_lambda_function -> AWSLambda
        google_cloudfunctions_function -> CloudFunctions
        """
        parts = resource_type.split("_")
        if parts[0] in ("aws", "google", "azurerm"):
            parts = parts[1:]
        # For AWS, prefix with AWS and use the first meaningful part
        if provider == "aws":
            return "AWS" + parts[0].capitalize() if parts else "AWS"
        else:
            return "".join(p.capitalize() for p in parts)

    @staticmethod
    def _to_camel_case(name: str) -> str:
        """Convert snake_case to camelCase."""
        parts = name.split("_")
        return parts[0] + "".join(p.capitalize() for p in parts[1:])

    @staticmethod
    def _to_pascal_case(name: str) -> str:
        """Convert snake_case to PascalCase."""
        return "".join(p.capitalize() for p in name.split("_"))


def generate_handler(resource: ResourceSchema, indent: int = 4) -> str:
    """Convenience function to generate a single handler.

    Args:
        resource: Parsed resource schema.
        indent: Indentation width.

    Returns:
        Python source code string.
    """
    gen = CodeGenerator(indent=indent)
    return gen.generate_handler(resource)
